version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis-service
    ports:
      - 6379:6379
    volumes:
      - /redis:/redis
    command: redis-server
    restart: always
  url:
    container_name: url-service
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    hostname: url-service
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - URL_SERVICE_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./url-service/main.go"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  qr:
    container_name: qr-service
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    hostname: qr-service
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - QR_SERVICE_PORT=4000
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./qr-service/main.go"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s