version: "3.9"
services:
  app:
    container_name: app
    depends_on:
      - cache
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    hostname: app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - APP_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: go run ./cmd/main.go
    restart: always
  cache:
    image: redis:latest
    container_name: redis-cache
    hostname: cache
    ports:
      - 6379:6379
    volumes:
      - /redis:/redis
    command: redis-server
    restart: unless-stopped

volumes:
  cache:
  app:
