version: '3'

services:

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - /redis:/redis
    command: redis-server
    restart: always

  app:
    container_name: app
    hostname: app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - APP_PORT=${APP_PORT}
      - GRPC_SERVER_HOST=${GRPC_SERVER_HOST}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always