version: "3.9"
services:
  app:
    container_name: app
    depends_on:
      - cache
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    hostname: app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - URL_SERVICE_PORT=3001
      - QR_SERVICE_PORT=3002
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - .:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./cmd/main.go"
    restart: always
  cache:
    image: redis:latest
    container_name: redis-cache
    hostname: cache
    ports:
      - 6379:6379
    volumes:
      - /redis:/redis
    command: redis-server
    restart: unless-stopped

volumes:
  cache:
  app:
